version: '3.8'

services:
  product-service:
    build:
      context: ./product-service
      target: ${NODE_ENV:-development}
    ports:
      - "5000:5000"
    env_file:
      - ./product-service/.env
    volumes:
      - ./product-service:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - microservice-network
    depends_on:
      - product-db

  product-db:
    image: mongo:6
    volumes:
      - product-db-data:/data/db
    restart: unless-stopped
    networks:
      - microservice-network

  order-service:
    build:
      context: ./order-service
      target: ${NODE_ENV:-development}
    ports:
      - "5001:5001"
    env_file:
      - ./order-service/.env
    volumes:
      - ./order-service:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - microservice-network
    depends_on:
      - order-db
      - product-service

  order-db:
    image: mongo:6
    volumes:
      - order-db-data:/data/db
    restart: unless-stopped
    networks:
      - microservice-network

volumes:
  product-db-data:
  order-db-data:

networks:
  microservice-network:
    driver: bridge
